# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_algo_pop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlgoPopDialog(object):
    def setupUi(self, AlgoPopDialog):
        AlgoPopDialog.setObjectName("AlgoPopDialog")
        AlgoPopDialog.resize(450, 298)
        self.buttonBox = QtWidgets.QDialogButtonBox(AlgoPopDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.continueCheckBox = QtWidgets.QCheckBox(AlgoPopDialog)
        self.continueCheckBox.setGeometry(QtCore.QRect(40, 130, 141, 31))
        self.continueCheckBox.setObjectName("continueCheckBox")
        self.continueFreqLineEdit = QtWidgets.QLineEdit(AlgoPopDialog)
        self.continueFreqLineEdit.setGeometry(QtCore.QRect(120, 160, 251, 31))
        self.continueFreqLineEdit.setObjectName("continueFreqLineEdit")
        self.fminlabel = QtWidgets.QLabel(AlgoPopDialog)
        self.fminlabel.setGeometry(QtCore.QRect(40, 40, 71, 31))
        self.fminlabel.setObjectName("fminlabel")
        self.fminLineEdit = QtWidgets.QLineEdit(AlgoPopDialog)
        self.fminLineEdit.setGeometry(QtCore.QRect(120, 40, 261, 31))
        self.fminLineEdit.setObjectName("fminLineEdit")
        self.fmaxlabel = QtWidgets.QLabel(AlgoPopDialog)
        self.fmaxlabel.setGeometry(QtCore.QRect(40, 90, 54, 12))
        self.fmaxlabel.setObjectName("fmaxlabel")
        self.fmaxLineEdit = QtWidgets.QLineEdit(AlgoPopDialog)
        self.fmaxLineEdit.setGeometry(QtCore.QRect(120, 80, 261, 31))
        self.fmaxLineEdit.setObjectName("fmaxLineEdit")

        self.retranslateUi(AlgoPopDialog)
        self.buttonBox.accepted.connect(AlgoPopDialog.accept)
        self.buttonBox.rejected.connect(AlgoPopDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AlgoPopDialog)

    def retranslateUi(self, AlgoPopDialog):
        _translate = QtCore.QCoreApplication.translate
        AlgoPopDialog.setWindowTitle(_translate("AlgoPopDialog", "算法设置"))
        self.continueCheckBox.setText(_translate("AlgoPopDialog", "从某一频率继续"))
        self.fminlabel.setText(_translate("AlgoPopDialog", "fmin"))
        self.fmaxlabel.setText(_translate("AlgoPopDialog", "fmax"))
