# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 720)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pageLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.pageLayout.setContentsMargins(28, 24, 28, 24)
        self.pageLayout.setSpacing(18)

        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setObjectName("titleLabel")
        self.pageLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.pageLayout.addWidget(self.subtitleLabel)

        self.workspaceLayout = QtWidgets.QHBoxLayout()
        self.workspaceLayout.setSpacing(18)

        self.setupPanel = QtWidgets.QFrame(self.centralwidget)
        self.setupPanel.setObjectName("setupPanel")
        self.setupPanel.setMinimumWidth(440)
        self.setupPanel.setMaximumWidth(560)
        self.setupLayout = QtWidgets.QVBoxLayout(self.setupPanel)
        self.setupLayout.setContentsMargins(22, 20, 22, 20)
        self.setupLayout.setSpacing(12)

        self.projectSectionLabel = QtWidgets.QLabel(self.setupPanel)
        self.projectSectionLabel.setObjectName("sectionLabel")
        self.setupLayout.addWidget(self.projectSectionLabel)
        self.projectRow = QtWidgets.QHBoxLayout()
        self.projectRow.setSpacing(10)
        self.dirNameLineEdit = QtWidgets.QLineEdit(self.setupPanel)
        self.dirNameLineEdit.setObjectName("dirNameLineEdit")
        self.projectRow.addWidget(self.dirNameLineEdit, 1)
        self.selectProjectDirButton = QtWidgets.QPushButton(self.setupPanel)
        self.selectProjectDirButton.setObjectName("selectProjectDirButton")
        self.projectRow.addWidget(self.selectProjectDirButton)
        self.setupLayout.addLayout(self.projectRow)

        self.cstSectionLabel = QtWidgets.QLabel(self.setupPanel)
        self.cstSectionLabel.setObjectName("sectionLabel")
        self.setupLayout.addWidget(self.cstSectionLabel)
        self.cstRow = QtWidgets.QHBoxLayout()
        self.cstRow.setSpacing(10)
        self.cstFilePathLineEdit = QtWidgets.QLineEdit(self.setupPanel)
        self.cstFilePathLineEdit.setObjectName("cstFilePathLineEdit")
        self.cstRow.addWidget(self.cstFilePathLineEdit, 1)
        self.selectCSTPathButton = QtWidgets.QPushButton(self.setupPanel)
        self.selectCSTPathButton.setObjectName("selectCSTPathButton")
        self.cstRow.addWidget(self.selectCSTPathButton)
        self.setupLayout.addLayout(self.cstRow)

        self.configurationSectionLabel = QtWidgets.QLabel(self.setupPanel)
        self.configurationSectionLabel.setObjectName("sectionLabel")
        self.setupLayout.addWidget(self.configurationSectionLabel)
        self.configurationRow = QtWidgets.QHBoxLayout()
        self.configurationRow.setSpacing(10)
        self.AlgSettingButton = QtWidgets.QPushButton(self.setupPanel)
        self.AlgSettingButton.setObjectName("AlgSettingButton")
        self.configurationRow.addWidget(self.AlgSettingButton)
        self.postProcessButton = QtWidgets.QPushButton(self.setupPanel)
        self.postProcessButton.setObjectName("postProcessButton")
        self.configurationRow.addWidget(self.postProcessButton)
        self.setupLayout.addLayout(self.configurationRow)

        self.executionSectionLabel = QtWidgets.QLabel(self.setupPanel)
        self.executionSectionLabel.setObjectName("sectionLabel")
        self.setupLayout.addWidget(self.executionSectionLabel)
        self.executionRow = QtWidgets.QHBoxLayout()
        self.executionRow.setSpacing(14)
        self.workerCountLabel = QtWidgets.QLabel(self.setupPanel)
        self.workerCountLabel.setObjectName("workerCountLabel")
        self.executionRow.addWidget(self.workerCountLabel)
        self.workerCountSpinBox = QtWidgets.QSpinBox(self.setupPanel)
        self.workerCountSpinBox.setMinimum(1)
        self.workerCountSpinBox.setMaximum(64)
        self.workerCountSpinBox.setValue(2)
        self.workerCountSpinBox.setObjectName("workerCountSpinBox")
        self.executionRow.addWidget(self.workerCountSpinBox)
        self.executionRow.addStretch(1)
        self.setupLayout.addLayout(self.executionRow)

        self.optionsRow = QtWidgets.QHBoxLayout()
        self.checkBox_CTN = QtWidgets.QCheckBox(self.setupPanel)
        self.checkBox_CTN.setEnabled(True)
        self.checkBox_CTN.setObjectName("checkBox_CTN")
        self.optionsRow.addWidget(self.checkBox_CTN)
        self.checkBox_SAFE = QtWidgets.QCheckBox(self.setupPanel)
        self.checkBox_SAFE.setEnabled(True)
        self.checkBox_SAFE.setObjectName("checkBox_SAFE")
        self.optionsRow.addWidget(self.checkBox_SAFE)
        self.optionsRow.addStretch(1)
        self.setupLayout.addLayout(self.optionsRow)
        self.setupLayout.addStretch(1)

        self.StartButton = QtWidgets.QPushButton(self.setupPanel)
        self.StartButton.setMinimumHeight(48)
        self.StartButton.setObjectName("StartButton")
        self.setupLayout.addWidget(self.StartButton)
        self.workspaceLayout.addWidget(self.setupPanel)

        self.logPanel = QtWidgets.QFrame(self.centralwidget)
        self.logPanel.setObjectName("logPanel")
        self.logPanelLayout = QtWidgets.QVBoxLayout(self.logPanel)
        self.logPanelLayout.setContentsMargins(18, 16, 18, 18)
        self.logPanelLayout.setSpacing(10)
        self.logHeaderLabel = QtWidgets.QLabel(self.logPanel)
        self.logHeaderLabel.setObjectName("sectionLabel")
        self.logPanelLayout.addWidget(self.logHeaderLabel)
        self.LogBoxLayout = QtWidgets.QHBoxLayout()
        self.LogBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.LogBoxLayout.setObjectName("LogBoxLayout")
        self.logPanelLayout.addLayout(self.LogBoxLayout, 1)
        self.workspaceLayout.addWidget(self.logPanel, 1)

        self.pageLayout.addLayout(self.workspaceLayout, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CST Batch Studio"))
        self.titleLabel.setText(_translate("MainWindow", "CST Batch Studio"))
        self.subtitleLabel.setText(
            _translate("MainWindow", "配置工程、计算策略与并发资源，并在右侧跟踪运行状态。")
        )
        self.projectSectionLabel.setText(_translate("MainWindow", "项目目录"))
        self.selectProjectDirButton.setText(_translate("MainWindow", "选择目录"))
        self.cstSectionLabel.setText(_translate("MainWindow", "CST 模板工程"))
        self.selectCSTPathButton.setText(_translate("MainWindow", "选择文件"))
        self.configurationSectionLabel.setText(_translate("MainWindow", "计算配置"))
        self.AlgSettingButton.setText(_translate("MainWindow", "扫描与算法"))
        self.postProcessButton.setText(_translate("MainWindow", "后处理结果"))
        self.executionSectionLabel.setText(_translate("MainWindow", "执行资源"))
        self.workerCountLabel.setText(_translate("MainWindow", "并发 Worker"))
        self.checkBox_CTN.setText(_translate("MainWindow", "继续运行"))
        self.checkBox_SAFE.setText(_translate("MainWindow", "安全模式"))
        self.StartButton.setText(_translate("MainWindow", "开始运行"))
        self.logHeaderLabel.setText(_translate("MainWindow", "运行日志"))
